### ISSUE TITLE
Initial 2 Accounts hinzufügen

### ISSUE THREAD

**Issue by NadineBisswang** [CodingColibri/Fallstudie#5]
Bitte im Backend mal Initial zwei User anlegen:
1 Admin (z.B. Prof. Dr. Richter als Studiengangsleiter) + Passwort
1 Dozent (z.B. Prof. Bimazubute) + Passwort 
Mann könnte man "dev" löschen und kann diese zwei Accounts für weitere Tests und später auch die Präsentation verwenden. 

@CodingColibri @Jobee0602

**Comment by NadineBisswang** [comment]
Am besten 2 Dozenten initial hinzufügen (Bimazubute und Heumüller oder so Ähnlich)..., damit ich testen kann, wie sich das auf die Kalendereinträge auswirkt :)

**Comment by CodingColibri** [comment]
![image](https://user-images.githubusercontent.com/54840955/80582098-724c4e00-8a0e-11ea-9fe3-decb2f5aaf94.png)
Done!

**Comment by NadineBisswang** [comment]
Super, danke:)
Könntet ihr die Accounts nochmal überprüfen/ in Postman testen? :)

![image](https://user-images.githubusercontent.com/56022020/81015320-c6b45b00-8e5e-11ea-928a-3e860f4b3ca9.png)

Ich kann mich mit keinem von beiden einloggen....

**Comment by CodingColibri** [comment]
Haben die eigentlich getestet und jetzt nochmal, funktioniert soweit. Wahrscheinlich kann er die nicht erstellen, weil unserer DB unterschiedlich ist. Kannst du den Konsolen Output nach dem Start schicken?
