### ISSUE TITLE
Backend Request Body für Vorlesung anlegen anpassen

### ISSUE THREAD

**Issue by NadineBisswang** [CodingColibri/Fallstudie#7]
Vom Backend wir gerade nur 1 Vorlesungsobjekt angenommen (siehe Bild zwei). Da ja mehrere Vorlesungen angelegt und abgeschickt werden können, brauchen wir das als Array. Das müsste genau so verarbeitet werden, wie bei "Semester anlegen": Die bestehenden Vorlesungen werden im Frontend vom Backend geladen (mit ID) und werden neue hinzugefügt haben die noch keine ID. Insgesamt wird das gesamte Array jedoch an das Backend geschickt und es wird -wie bei Semester anlegen- geprüft:
- Gibt es die Vorlesung mit der ID schon? Wenn ja -> Vorlesung updaten und nicht neu anlegen
- Hat die Vorlesung noch keine ID? Neu anlegen und ID mitschicken.
Der 1. Screenshot zeigt den Payload, den ich mit ans Backend schicke und der verarbeitet werden sollte :) 

![image](https://user-images.githubusercontent.com/56022020/81289235-58da8000-9066-11ea-9e36-0bbd07c8bdaf.png)
![image](https://user-images.githubusercontent.com/56022020/81289272-698af600-9066-11ea-80e0-52ef9ae1fc53.png)

**Comment by CodingColibri** [comment]
Wie meinst du ID mitschicken? So wie bei bei den Semestern einfach alle Vorlesungen mitschicken? :)

**Comment by NadineBisswang** [comment]
Genau, also wie bei den Semestern schicke ich alle Vorlesungen mit bzw. bekomme vom Backend auch immer alle wieder zurück :)

**Comment by CodingColibri** [comment]
Perfekt, schau mal ob es so passt :)

**Comment by NadineBisswang** [comment]
![image](https://user-images.githubusercontent.com/56022020/81297178-300cb780-9073-11ea-82b0-145fa0a462ea.png)

Leider noch nicht ganz -> Also update ist kein Attribut von Vorlesung eigentlich....

**Comment by CodingColibri** [comment]
Ne genau, update ist eine Methode, das Vorlesung von db.Model erbt. Hab nochmal was angepasst. Gehts jetzt?

**Comment by NadineBisswang** [comment]
Ja :) :) :) :) :) Super :)
